#! /usr/bin/env php

<?php

use App\ImportItemsCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Mysql importer for csv', '1.0');

$app->add(new ImportItemsCommand);

$app->run();